# Generated by Django 4.0.5 on 2022-06-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField(max_length=255)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_At', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre_comercial', models.CharField(max_length=50)),
                ('rnc', models.CharField(max_length=9, unique=True)),
                ('cuenta_contable', models.CharField(max_length=9, unique=True)),
                ('estado', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('porciento_comision', models.IntegerField()),
                ('estado', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_At', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
