# Generated by Django 4.0.5 on 2022-07-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cuenta_contable',
            field=models.IntegerField(max_length=2),
        ),
    ]
