# Generated by Django 4.0.5 on 2022-06-30 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='update_At',
            new_name='update_at',
        ),
    ]
