# Generated by Django 4.0.5 on 2022-07-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_clientes_cuenta_contable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cuenta_contable',
            field=models.IntegerField(),
        ),
    ]
