# Generated by Django 4.0.5 on 2022-07-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_facturacion_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacion',
            name='accounting_entry_id',
            field=models.IntegerField(null=True),
        ),
    ]
